pipeline {
    agent any
    stages {
        stage('Barcelona') {
            steps {
                script {
                    println 'La ciudad de Barcelona tiene una poblacion final de 80000.0 habitantes'
                }
            }
        }
        stage('Madrid') {
            steps {
                script {
                    println 'La ciudad de Madrid tiene una poblacion final de 800000.0 habitantes'
                }
            }
        }
        stage('Malaga') {
            steps {
                script {
                    println 'La ciudad de Malaga tiene una poblacion final de 40000.0 habitantes'
                }
            }
        }
        stage('Sevilla') {
            steps {
                script {
                    println 'La ciudad de Sevilla tiene una poblacion final de 64000.0 habitantes'
                }
            }
        }
    }
}