pipeline {
    agent any
    stages {
        stage('Barcelona') {
            steps {
                script {
                    println 'La ciudad de Barcelona tiene una población final de 80000.0 habitantes'
                }
            }
        }
        stage('Madrid') {
            steps {
                script {
                    println 'La ciudad de Madrid tiene una población final de 800000.0 habitantes'
                }
            }
        }
        stage('Málaga') {
            steps {
                script {
                    println 'La ciudad de Málaga tiene una población final de 40000.0 habitantes'
                }
            }
        }
        stage('Sevilla') {
            steps {
                script {
                    println 'La ciudad de Sevilla tiene una población final de 64000.0 habitantes'
                }
            }
        }
    }
}